{
  "openapi": "3.0.0",
  "info": {
    "title": "Serious Game Server API",
    "description": "This is the documentation of the Serious Game Server API. Find the repository [on github](https://github.com/robinlarondelle/serious-game-server)",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/"
    }
  ],
  "tags": [
    {
      "name": "Organisation",
      "description": "Everything about Organisation"
    },
    {
      "name": "Department",
      "description": "A Department is a subdivision of a Organisation"
    },
    {
      "name": "Play",
      "description": "A play is a single game a user plays, which is saved per Department"
    },
    {
      "name": "Question",
      "description": "All the questions that belong to an Organisation"
    }
  ],
  "components": {
    "schemas": {
      "ApiError": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "error",
          "message",
          "code"
        ]
      },
      "Answer": {
        "type": "object",
        "properties": {
          "answer": {
            "type": "string"
          },
          "stats": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": {
                "type": "integer"
              }
            }
          }
        },
        "required": [
          "answer",
          "stats"
        ]
      },
      "Question": {
        "type": "object",
        "properties": {
          "question": {
            "type": "string"
          },
          "answers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "answer": {
                  "type": "string"
                },
                "stats": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": {
                      "type": "integer"
                    }
                  }
                }
              },
              "required": [
                "answer",
                "stats"
              ]
            }
          }
        },
        "required": [
          "question",
          "answers"
        ]
      },
      "Play": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date"
          },
          "results": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "question": {
                  "type": "string"
                },
                "answer": {
                  "type": "string"
                },
                "answerStats": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": {
                      "type": "integer"
                    }
                  }
                }
              },
              "required": [
                "question",
                "answer",
                "answerStats"
              ]
            }
          }
        },
        "required": [
          "results"
        ]
      },
      "Department": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "_id"
        ]
      },
      "Organisation": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "integer",
            "minimum": 100000,
            "maximum": 999999
          },
          "name": {
            "type": "string"
          },
          "pin": {
            "type": "integer",
            "minimum": 100000,
            "maximum": 999999
          },
          "departments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "integer"
                },
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "_id"
              ]
            }
          },
          "questions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "question": {
                  "type": "string"
                },
                "answers": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "answer": {
                        "type": "string"
                      },
                      "stats": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "additionalProperties": {
                            "type": "integer"
                          }
                        }
                      }
                    },
                    "required": [
                      "answer",
                      "stats"
                    ]
                  }
                }
              },
              "required": [
                "question",
                "answers"
              ]
            }
          }
        },
        "required": [
          "_id",
          "name",
          "pin"
        ]
      }
    },
    "parameters": {
      "orgID": {
        "name": "orgID",
        "in": "path",
        "description": "Organisation ID (the Organisation PIN = Organisation ID)",
        "required": true,
        "schema": {
          "type": "integer"
        }
      },
      "depID": {
        "name": "depID",
        "in": "path",
        "description": "Department ID",
        "required": true,
        "schema": {
          "type": "integer"
        }
      },
      "queID": {
        "name": "queID",
        "in": "path",
        "description": "Question ID",
        "required": true,
        "schema": {
          "type": "integer"
        }
      },
      "playID": {
        "name": "playID",
        "in": "path",
        "description": "Play ID",
        "required": true,
        "schema": {
          "type": "integer"
        }
      }
    },
    "responses": {
      "404": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                },
                "code": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "required": [
                "error",
                "message",
                "code"
              ]
            }
          }
        }
      },
      "default": {
        "description": "Server error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                },
                "code": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "required": [
                "error",
                "message",
                "code"
              ]
            },
            "example": {
              "error": "ServerError",
              "message": "Something went wrong. {error}",
              "code": 400
            }
          }
        }
      },
      "duplicate": {
        "description": "Duplicate",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                },
                "message": {
                  "type": "string"
                },
                "code": {
                  "type": "integer",
                  "format": "int32"
                }
              },
              "required": [
                "error",
                "message",
                "code"
              ]
            }
          }
        }
      }
    }
  },
  "paths": {
    "/organisation": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get all the organisations",
        "description": "This endpoint will get all the organisations in the dataset, Including their Departments, Questions and Players. Using this endpoint as an Organisation is not desired.\n",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "tags": [
          "Organisation"
        ],
        "summary": "Add a new Organisation",
        "description": "Create a new organisation. The name and the PIN of the organisation has to be unique.  The PIN property in the body is optional. A real life organisation should not use this endpoint.  Only the game admin should be able to create new organisations.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "pin": {
                    "type": "integer",
                    "minimum": 100000,
                    "maximum": 999999
                  }
                },
                "required": [
                  "name"
                ]
              },
              "examples": {
                "onlyName": {
                  "summary": "Name only",
                  "description": "Supply a name only and a PIN will be generated",
                  "value": {
                    "name": "HotRed Inc."
                  }
                },
                "withPin": {
                  "summary": "Name and PIN",
                  "description": "Supply a PIN (optional) and, if available, that will be your PIN and ID",
                  "value": {
                    "name": "HotRed Inc.",
                    "pin": 123456
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                },
                "example": {
                  "_id": 123456,
                  "name": "HotRed Inc.",
                  "pin": 123456,
                  "departments": [],
                  "questions": [],
                  "plays": []
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/duplicate"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID": {
      "get": {
        "tags": [
          "Organisation"
        ],
        "summary": "Get a specific Organisation",
        "description": "a single organisation with the given ID",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/department": {
      "get": {
        "tags": [
          "Department"
        ],
        "summary": "Get all departments from the given Organisation",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Department"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "post": {
        "tags": [
          "Department"
        ],
        "summary": "Add a new department to the given Organisation",
        "description": "Add a new department to a organisation. It's important that the department name is unique.\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Department"
              },
              "example": {
                "name": "IT department"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                },
                "example": {
                  "_id": 123456,
                  "name": "HotRed Inc.",
                  "pin": 123456,
                  "departments": [
                    "\\your created department here\\"
                  ],
                  "questions": [],
                  "plays": []
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/department/:depID": {
      "get": {
        "tags": [
          "Department"
        ],
        "summary": "Gets the department with the given ID",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Department"
                },
                "example": {
                  "_id": "32fdas89a3r",
                  "name": "IT department"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "put": {
        "tags": [
          "Department"
        ],
        "summary": "Updates the department with the given ID",
        "description": "Update a department with the given ID of an organisation. If successfull, returns the complete organisation with the updated departments\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Department"
              },
              "example": {
                "name": "Marketing department"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "delete": {
        "tags": [
          "Department"
        ],
        "summary": "Deletes the department with the given ID",
        "description": "Deletes a department with the given ID of an organisation. If successfull, returns the complete organisation with the updated departments\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/department/:depID/play": {
      "get": {
        "tags": [
          "Play"
        ],
        "summary": "Get all the Plays from a department",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Play"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "post": {
        "tags": [
          "Play"
        ],
        "summary": "Add a new Play to a Department",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Play"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Play"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/department/:depID/play/:playID": {
      "get": {
        "tags": [
          "Play"
        ],
        "summary": "something",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          },
          {
            "$ref": "#/components/parameters/playID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Play"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "delete": {
        "tags": [
          "Play"
        ],
        "summary": "something",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/depID"
          },
          {
            "$ref": "#/components/parameters/playID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Play"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/question": {
      "get": {
        "tags": [
          "Question"
        ],
        "summary": "Get all Questions from the given Organisation",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Question"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "post": {
        "tags": [
          "Question"
        ],
        "summary": "Add a new question to the given Organisation",
        "description": "Add a new Question to a organisation. The Question-Awnsers pairs need to be unique\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Question"
              },
              "example": {
                "question": "Someone offers you a bribe. What do you do?",
                "answers": [
                  {
                    "answer": "Take the money and save his number for further inquiries",
                    "stats": {
                      "integrity": -10,
                      "loyalty": 5,
                      "trustworthy": -5
                    }
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                },
                "example": {
                  "_id": 123456,
                  "name": "HotRed Inc.",
                  "pin": 123456,
                  "departments": [],
                  "questions": [
                    {
                      "question": "Someone offers you a bribe. What do you do?",
                      "answers": [
                        {
                          "answer": "Take the money and save his number for further inquiries",
                          "stats": [
                            {
                              "integrity": -10
                            },
                            {
                              "loyalty": 5
                            },
                            {
                              "trustworthy": -5
                            }
                          ]
                        }
                      ]
                    }
                  ],
                  "plays": []
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    },
    "/organisation/:orgID/question/:queID": {
      "get": {
        "tags": [
          "Question"
        ],
        "summary": "Gets the question with the given ID",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/queID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Question"
                },
                "example": {
                  "question": "Someone offers you a bribe. What do you do?",
                  "answers": [
                    {
                      "answer": "Take the money and save his number for further inquiries",
                      "stats": [
                        {
                          "integrity": -10
                        },
                        {
                          "loyalty": 5
                        },
                        {
                          "trustworthy": -5
                        }
                      ]
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "put": {
        "tags": [
          "Question"
        ],
        "summary": "Updates the question with the given ID",
        "description": "Update a Question with the given ID of an organisation. If successfull, returns the complete organisation with the updated questions\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/queID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Question"
              },
              "example": {
                "question": "Someone offers you a cookie. What do you do?",
                "answers": [
                  {
                    "answer": "Take the money and save his number for further inquiries",
                    "stats": [
                      {
                        "integrity": -10
                      },
                      {
                        "loyalty": 5
                      },
                      {
                        "trustworthy": -5
                      }
                    ]
                  }
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Question"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      },
      "delete": {
        "tags": [
          "Question"
        ],
        "summary": "Deletes the question with the given ID",
        "description": "Deletes a question with the given ID of an organisation. If successfull, returns the complete organisation with the updated questions\n",
        "parameters": [
          {
            "$ref": "#/components/parameters/orgID"
          },
          {
            "$ref": "#/components/parameters/queID"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Organisation"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "default": {
            "$ref": "#/components/responses/default"
          }
        }
      }
    }
  }
}